### ISSUE TITLE
Add support for comments

### ISSUE THREAD

**Issue by ausi** [madeyourday/contao-rocksolid-antispam#2]
Add support for the comments form.

**Comment by fenepedia** [comment]
+1

**Comment by jscholtysik** [comment]
+1

**Comment by ausi** [comment]
Since Contao 4.4 a [similar anti-spam protection](https://github.com/contao/core-bundle/pull/832) is built into the core which works in all forms. Therefore I think it is not necessary to add this feature to the extension.
