### ISSUE TITLE
Add support for registration and other “dynamic” forms

### ISSUE THREAD

**Issue by ausi** [madeyourday/contao-rocksolid-antispam#4]
See http://help.rocksolidthemes.com/discussions/contao/13324

**Comment by felixpfeiffer** [comment]
Hallo,
eine Frage, wie der Stand bzgl. dieses Features ist?
Gruß,
Felix

**Comment by ausi** [comment]
Sobald es Updates zu diesem Thema gibt, werden diese hier vermerkt.

**Comment by mandrael** [comment]
+1

**Comment by ausi** [comment]
Since Contao 4.4 a [similar anti-spam protection](https://github.com/contao/core-bundle/pull/832) is built into the core which works in all forms. Therefore I think it is not necessary to add this feature to the extension.
