### ISSUE TITLE
JS Error with Terminal42\contao-conditionalformfields

### ISSUE THREAD

**Issue by chibko** [madeyourday/contao-rocksolid-antispam#9]
Hi,

Sometimes, JS error occurs on FE on form with Terminal42\contao-conditionalformfields extension installed.
The brower console says "SyntaxError: identifier starts immediately after numeric literal".
I dig it and found that the problem is the random rsas fieldname may start with digit witch cause the conditionalformfields js script to fail.
Can you adjust your php getRandomString function so that string always start by letter ?
Regards,
Stéphane

**Comment by ausi** [comment]
> I dig it and found that the problem is the random rsas fieldname may start with digit witch cause the conditionalformfields js script to fail.

`name`s of `<input>`s are allowed to start with a digit, furthermore there are probably other input names that would be invalid as a JavaScript identifier. I think this needs to be fixed in the conditionalformfields script.

**Comment by chibko** [comment]
I agree there's no specific rules for input name, but I think most developers avoid naming there input name with starting number et avoid special character too.
I will ask Terminal42 if they can solve this. 
In my case i have modifiy your function getRandomString like this

protected static function getRandomString() {
		return "RS".rtrim(strtr(base64_encode(pack(
			'n8',
			mt_rand(0,65535),
			mt_rand(0,65535),
			mt_rand(0,65535),
			mt_rand(0,65535),
			mt_rand(0,65535),
			mt_rand(0,65535),
			mt_rand(0,65535),
			mt_rand(0,65535)
		)), '+/', '-_'), '=');
	}`
No disadvantages?

**Comment by ausi** [comment]
> No disadvantages?

I don’t know. But as the string can also include the `-` character, wouldn’t this also trigger an error as it is not allowed inside JavaScript identifiers?

Can you point me to where exactly in the script this error occurs?

**Comment by chibko** [comment]
The JS Code below i added a comment where ERROR OCCURS

(function () {
    "use strict";
    const initialized = [];

    function init (node) {
        node.querySelectorAll('fieldset[data-cff-condition]').forEach(function (el) {
            if (initialized.includes(el)) {
                return;
            }

            initialized.push(el);

            const form = el.form;
            const condition = el.getAttribute('data-cff-condition');

            Array.from(form.elements).forEach(function (control) {
                control.addEventListener('change', function () {
                    toggleFieldset(el, condition, getFormData(form));
                });
            })

            toggleFieldset(el, condition, getFormData(form));
        });
    }

    function toggleFieldset (fieldset, condition, formData) {
        let fnBody = '"use strict";';
        fnBody += 'function in_array (needle, haystack) { return Array.isArray(haystack) ? haystack.includes(needle) : false; };';
        fnBody += 'function str_contains (haystack, needle) { return String(haystack).includes(needle) };'

        formData.forEach(function (value, key) {
            if (String(key).includes('-') || String(key).includes('[')) {
                console.warn(`terminal42/contao-conditionalformfields: skipping "${key}", special characters [-] and brackets are not supported in JavaScript variables.`);
            } else {
                fnBody += `const ${key} = values.get('${key}');`;
            }
        });

        fnBody += `return ${condition};`;

        // ERROR OCCURS HERE BECAUSE fnBody is Worng
       // The script warns if there's a - in the name 

        let fn = new Function('values', fnBody); 

        if (fn.call(undefined, formData)) {
            fieldset.disabled = false
            fieldset.style.display = '';
        } else {
            fieldset.disabled = true
            fieldset.style.display = 'none';
        }
    }

    function getFormData (form) {
        const data = new Map();
        const formData = new FormData(form);

        if (form.hasAttribute('data-cff-previous')) {
            const previous = JSON.parse(form.getAttribute('data-cff-previous'));
            Object.keys(previous).forEach(function (key) {
                data.set(key, previous[key]);
            });
        }

        for (let { 0: name, 1: value } of formData) {
            // Array
            if (name.substring(name.length - 2) === '[]') {
                name = name.substring(0, name.length - 2);

                if (!(data.get(name) instanceof Array)) {
                    data.set(name, []);
                }

                data.get(name).push(value);
            } else {
                data.set(name, value);
            }
        }

        // Initialize empty values (e.g. no radio option selected)
        Array.from(form.elements).forEach(function (control) {
            if (!control.name) {
                return;
            }

            let name = control.name;
            let value = '';

            if (name.substring(name.length - 2) === '[]') {
                name = name.substring(0, name.length - 2);
                value = [];
            }

            if (!data.has(name)) {
                data.set(control.name, value);
            }
        })

        return data;
    }

    function load () {
        init(document);
        new MutationObserver(function (mutationsList) {
            for (const mutation of mutationsList) {
                if (mutation.type === 'childList') {
                    mutation.addedNodes.forEach(function (element) {
                        if (element.querySelectorAll) {
                            init(element)
                        }
                    })
                }
            }
        }).observe(document, {
            attributes: false,
            childList: true,
            subtree: true
        });
    }

    if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', load);
    } else {
        load();
    }
})();

**Comment by ausi** [comment]
The code line 

```js
if (String(key).includes('-') || String(key).includes('[')) {
```

needs to be adjusted to also check for digits at the beginning of the string. 
For example like this:

```js
if (String(key).includes('-') || String(key).includes('[') || !isNaN(String(key)[0])) {
```

This should fix the issue for all types of fields.

**Comment by chibko** [comment]
Thank you ausi  👍
